#!/usr/bin/env python3
"""Container start scripts for every llgenie engine image (issue #98).

`make install` builds nothing natively. It detects this host's backend (cuda,
rocm, vulkan or cpu; LLAMA_BACKEND / ARCH= mock it) and PULLS the matching
published, CI-tested image of each engine from LLGENIE_REGISTRY (GHCR,
default ghcr.io/asimov-agent). Only images for this backend are pulled (an engine
without one falls back to its cpu image). It builds an image only with --build
(BUILD=1). By default it installs the CORE set: both llama.cpp trees (the two
shims below). ENGINES=all installs every engine; any other engine is pulled the
first time `llgenie --pick/--engine` selects it (`--ensure <id>`). Then it
writes a start script into ~/bin:

  ~/bin/llgenie-engine-<id>   docker-runs the engine image:
                                llgenie-engine-<id> --version       engine version
                                llgenie-engine-<id> <model> [port]  serve <model> as
                                  llm-local on 127.0.0.1:${PORT:-11434}/v1
  ~/bin/llama-server          shim: the stock llama.cpp image (ggml-org)
  ~/bin/prism-server          shim: the Prism llama.cpp image
                              Both take the llama-server CLI and run it in the
                              container; llgenie.py picks one by the card's tree
                              (Prism on cards <= 24 GB, like detect_server).

  python3 scripts/install_engine_launchers.py [--bin DIR] [--arch A] [--engines all|id,id] [--build]
  python3 scripts/install_engine_launchers.py --bin DIR --ensure <engine-id>
  python3 scripts/install_engine_launchers.py --bin DIR --test

--test runs every start script with --version (each is a docker run of its
image) and fails unless every one prints a version. Metal-only engines have no
container image, so no script is written for them. Stdlib only.
"""
from __future__ import annotations

import argparse
import re
import shutil
import json
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
import engine_image as ei  # noqa: E402

PARAMS = REPO / "containers" / "engines" / "params"
PREFIX = "llgenie-engine-"
# same GPU passthrough as `make run-engine` (engine_skills.RUN_ARGS): the host
# driver is mounted into the container at run time
import engine_skills as es  # noqa: E402
GPU_FLAGS = {k: " ".join(v) for k, v in es.RUN_ARGS.items()}


CORE_ENGINES = ["llama.cpp", "llama.cpp-prism"]  # the two llama.cpp shims; others on demand
RUNTIME_DOWN = ("container runtime '{rt}' does not answer (`{rt} info` failed): start its engine "
                "(macOS: colima start --runtime docker --vm-type vz --vz-rosetta) or point RUNTIME at a docker CLI")


def detected_arch() -> str:
    """cuda | rocm | vulkan | cpu for this host (LLAMA_BACKEND mocks it)."""
    try:
        import detect_server as d
        b = d.detect_all().get("backend")
        if b == "cpu" and shutil.which("rocminfo") and es.rocm_gfx_targets():
            b = "rocm"
        return {"cuda": "cuda", "rocm": "rocm", "vulkan": "vulkan"}.get(b, "cpu")
    except Exception:  # noqa: BLE001
        return "cpu"


def variant_for(engine: str, arch: str) -> str | None:
    """The engine's image variant for this backend; cpu when it has none."""
    variants = [v for v in json.loads((PARAMS / f"{engine}.json").read_text()).get("variants") or {}
                if not ei.disabled(engine, v)]  # disabled images are never pulled (ei.DISABLED)
    return arch if arch in variants else ("cpu" if "cpu" in variants else None)


def script_name(engine: str) -> str:
    return PREFIX + engine.replace(".", "-").replace("/", "-")


def ensure_image(engine: str, variant: str, build: bool) -> str | None:
    """Local tag of the engine image: present, pulled from the registry, or built."""
    spec = ei.resolve(engine, None, variant)
    if ei._available(spec["tag"]):
        return spec["tag"]
    if build and ei.build(spec) == 0:
        return spec["tag"]
    return None


def launcher(engine: str, variant: str, tag: str, models: str, platform: str = "") -> str:
    name = script_name(engine)
    plat = f" --platform {platform}" if platform else ""
    return f"""#!/usr/bin/env bash
# Generated by `make install` (scripts/install_engine_launchers.py). Do not edit.
# {engine} ({variant}) runs ONLY through its container image {tag}.
#   {name} --version          engine version (docker run ... version)
#   {name} <model> [port]     serve <model> as llm-local on 127.0.0.1:${{PORT:-11434}}/v1
set -euo pipefail
IMAGE="${{LLGENIE_IMAGE:-{tag}}}"
case "${{1:-}}" in
  --version|-v|version) exec {ei.RUNTIME} run --rm{plat} "$IMAGE" version ;;
  ""|-h|--help) sed -n '3,5p' "$0"; exit 0 ;;
esac
MODEL="$1"; PORT="${{2:-${{PORT:-11434}}}}"
MODELS="${{LLGENIE_MODELS_DIR:-{models}}}"
case "$MODEL" in "$MODELS"/*) MODEL="/models/${{MODEL#"$MODELS"/}}" ;; esac
name="llgenie-{engine.replace('.', '-')}-$PORT"
{ei.RUNTIME} rm -f "$name" >/dev/null 2>&1 || true
trap '{ei.RUNTIME} rm -f "$name" >/dev/null 2>&1' EXIT INT TERM
gpu=({GPU_FLAGS.get(variant, '')}); [ -n "${{LLGENIE_NO_GPU:-}}" ] && gpu=({GPU_FLAGS['cpu']})  # LLGENIE_NO_GPU=1: GPU image on CPU
{ei.RUNTIME} run --rm{plat} --name "$name" "${{gpu[@]}}" \\
  -p "127.0.0.1:$PORT:11434" -v "$MODELS:/models" -e HF_TOKEN \\
  -e "LLGENIE_MODEL=$MODEL" "$IMAGE" serve &
wait $!
"""


def server_binary(engine: str, variant: str) -> str:
    """llama-server's path inside the image: the first word of the frozen launch
    line (/app/llama-server in ggml-org images, a build-<arch>/bin path in the
    Prism/LaurentZuijdwijk source builds)."""
    params = json.loads((es.PARAMS_DIR / f"{engine}.json").read_text())
    return params["variants"][variant]["launch"].split()[0]


SERVER_SHIMS = {"llama.cpp": "llama-server", "llama.cpp-prism": "prism-server"}


def llama_server_shim(tag: str, variant: str, binary: str = "/app/llama-server",
                      name: str = "llama-server", platform: str = "") -> str:
    bindir = binary.rsplit("/", 1)[0]
    plat = f" --platform {platform}" if platform else ""
    return f"""#!/usr/bin/env bash
# Generated by `make install`: {name} (llama.cpp llama-server) through its container image
# ({tag}). llgenie.py calls it like the native binary; model files are mounted
# read-only at the same path and the port is published on the same host:port.
set -euo pipefail
IMAGE="${{LLGENIE_IMAGE:-{tag}}}"
case "${{1:-}}" in --version|version) exec {ei.RUNTIME} run --rm{plat} "$IMAGE" version ;; esac
args=(); mounts=(); port=8080; host=127.0.0.1
while [[ $# -gt 0 ]]; do
  case "$1" in
    -m|--model|-md|--model-draft|--mmproj)
      f="$(readlink -f "$2")"; mounts+=(-v "$(dirname "$f"):$(dirname "$f"):ro"); args+=("$1" "$f"); shift 2 ;;
    --port) port="$2"; args+=(--port "$2"); shift 2 ;;
    --host) host="$2"; args+=(--host 0.0.0.0); shift 2 ;;
    *) args+=("$1"); shift ;;
  esac
done
# one container per port, named so it can always be found and removed: a
# killed shim (SIGTERM/SIGKILL from a caller) must not leave the server running.
name="llgenie-{name}-$port"
{ei.RUNTIME} rm -f "$name" >/dev/null 2>&1 || true
trap '{ei.RUNTIME} rm -f "$name" >/dev/null 2>&1' EXIT INT TERM
gpu=({GPU_FLAGS.get(variant, '')}); [ -n "${{LLGENIE_NO_GPU:-}}" ] && gpu=({GPU_FLAGS['cpu']})  # LLGENIE_NO_GPU=1: GPU image on CPU
{ei.RUNTIME} run --rm{plat} --name "$name" "${{gpu[@]}}" -p "$host:$port:$port" "${{mounts[@]}}" \\
  -e LD_LIBRARY_PATH={bindir} --entrypoint {binary} "$IMAGE" "${{args[@]}}" &
wait $!
"""


def cuda_cdi_ready() -> bool:
    """nvidia-container-toolkit generated the CDI spec that mounts the host driver."""
    r = subprocess.run(["nvidia-ctk", "cdi", "list"], capture_output=True, text=True) \
        if shutil.which("nvidia-ctk") else None
    return bool(r and r.returncode == 0 and "nvidia.com/gpu=all" in r.stdout)


def install(bindir: Path, arch: str, build: bool, only: list[str] | None = None) -> int:
    if arch == "cuda" and not os.environ.get("LLGENIE_NO_GPU") and not cuda_cdi_ready():
        print("[install] FAIL cuda host without the NVIDIA CDI spec: the engine containers could not "
              "use the host driver. Install nvidia-container-toolkit and run\n"
              "          sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml")
        return 1
    bindir.mkdir(parents=True, exist_ok=True)
    models = os.environ.get("LLGENIE_MODELS_DIR", str(Path.home() / "models"))
    written, failed = {}, []
    every = sorted(json.loads(pf.read_text())["id"] for pf in PARAMS.glob("*.json"))
    wanted = every if only == ["all"] else (only or CORE_ENGINES)
    print(f"[install] backend {arch}: {', '.join(wanted)}"
          f"{'' if build else ' (pull published images only)'}")
    for engine in wanted:
        if engine not in every:
            failed.append(engine)
            print(f"[install] FAIL {engine}: unknown engine (have {', '.join(every)})")
            continue
        p = json.loads((PARAMS / f"{engine}.json").read_text())
        variant = variant_for(engine, arch)
        if not variant:
            print(f"[install] {engine}: no {arch}/cpu image (has {', '.join(p.get('variants') or {})}) - skipped")
            continue
        tag = ensure_image(p["id"], variant, build)
        if not tag:
            failed.append(p["id"])
            why = "the build failed" if build else f"not published in {ei.REGISTRY or '(no LLGENIE_REGISTRY)'}"
            if not ei.runtime_answers(ei.RUNTIME):
                # a CLI with no engine behind it (docker CLI next to Colima's containerd,
                # a stopped VM) is not an unpublished image (issue #112)
                why = RUNTIME_DOWN.format(rt=ei.RUNTIME)
            print(f"[install] FAIL {p['id']}/{variant}: {why}")
            continue
        out = bindir / script_name(p["id"])
        plat = ei.image_platform(tag)  # run the image as what it is (no amd64-on-arm64 warning)
        out.write_text(launcher(p["id"], variant, tag, models, plat))
        out.chmod(0o755)
        written[p["id"]] = (variant, tag, plat)
        print(f"[install] {out} -> {tag}")
    # one shim per llama.cpp tree, named after its server (issue #98):
    #   ~/bin/llama-server  -> stock llama.cpp image (ggml-org, /app/llama-server)
    #   ~/bin/prism-server  -> Prism llama.cpp image (its build-<arch>/bin/llama-server)
    # llama_serve.resolve_llama_server picks one by the card's tree.
    for engine, name in SERVER_SHIMS.items():
        hit = written.get(engine)
        if not hit:
            continue
        shim = bindir / name
        if shim.is_symlink() or shim.exists():
            shim.unlink()
        shim.write_text(llama_server_shim(hit[1], hit[0], server_binary(engine, hit[0]), name, hit[2]))
        shim.chmod(0o755)
        print(f"[install] {shim} -> {hit[1]} ({name} in its container)")
    return 1 if failed else 0


def ensure(bindir: Path, engine: str, arch: str, build: bool) -> int:
    """`llgenie --pick/--engine`: pull ONE engine's image for this backend (if not
    yet local) and write its start script. Idempotent and fast when present."""
    script = bindir / script_name(engine)
    variant = variant_for(engine, arch) if (PARAMS / f"{engine}.json").exists() else None
    if not variant:
        print(f"[install] FAIL {engine}: no {arch}/cpu image")
        return 1
    tag = ei.resolve(engine, None, variant)["tag"]
    if script.exists() and tag in script.read_text() and ei.image_exists(tag):
        return 0
    print(f"[install] {engine}: pulling the {variant} image (first use)", flush=True)
    return install(bindir, arch, build, [engine])


VERSION_RE = re.compile(r"\d+\.\d+")
# Lines the container runtime itself prints (never the engine's version), e.g.
#   WARNING: The requested image's platform (linux/amd64) does not match ... (docker)
#   time="..." level=warning msg="force cleanup timed out for container ..." (nerdctl)
RUNTIME_NOISE_RE = re.compile(r'^\s*(WARNING:|time="[^"]*" level=)')


def version_ok(returncode: int, stdout: str, stderr: str) -> tuple[bool, str]:
    """`<script> --version` passed: exit 0 and the engine printed a version number on
    ANY line of stdout or stderr that is not runtime noise (issue #112: the runtime may
    print a warning after the engine's version line, so the last line is not the
    version). Returns (ok, the line to report: the version line, else the last line)."""
    lines = [ln for ln in (stdout + "\n" + stderr).splitlines() if ln.strip()]
    hits = [ln for ln in lines if VERSION_RE.search(ln) and not RUNTIME_NOISE_RE.match(ln)]
    line = hits[-1] if hits else (lines[-1] if lines else "")
    return returncode == 0 and bool(hits), line


def test(bindir: Path) -> int:
    scripts = sorted(bindir.glob(PREFIX + "*"))
    scripts += [bindir / n for n in SERVER_SHIMS.values() if (bindir / n).exists()]
    if not scripts:
        print(f"[test-built-engine] no {PREFIX}* scripts in {bindir}; run make install")
        return 1
    fails = 0
    for s in scripts:
        r = subprocess.run([str(s), "--version"], capture_output=True, text=True, timeout=600)
        ok, line = version_ok(r.returncode, r.stdout, r.stderr)
        fails += not ok
        print(f"[test-built-engine] {'OK  ' if ok else 'FAIL'} {s.name} --version: {line[:150]}")
    print(f"[test-built-engine] {len(scripts) - fails} ok, {fails} failed")
    return 1 if fails else 0


MARKER = "Generated by `make install`"


def uninstall(bindir: Path, purge_images: bool = False) -> int:
    """Undo `make install`: stop running engine containers, remove the start
    scripts and the llama-server shim (only files this script wrote, or a stale
    symlink from the old native install). Engine images are kept as a cache
    unless purge_images; no source tree or model is ever touched."""
    removed = []
    for s in sorted(bindir.glob(PREFIX + "*")):
        if s.is_symlink() or MARKER in s.read_text(errors="ignore"):
            s.unlink()
            removed.append(s.name)
    for n in SERVER_SHIMS.values():
        shim = bindir / n
        if shim.is_symlink() or (shim.is_file() and MARKER in shim.read_text(errors="ignore")):
            shim.unlink()
            removed.append(shim.name)
    r = subprocess.run([ei.RUNTIME, "ps", "-q", "--filter", "name=^llgenie-"], capture_output=True, text=True)
    running = r.stdout.split()
    if running:
        subprocess.run([ei.RUNTIME, "rm", "-f", *running], capture_output=True)
    print(f"[uninstall] removed {len(removed)} file(s) from {bindir}: {' '.join(removed) or '-'}")
    print(f"[uninstall] stopped {len(running)} running llgenie engine container(s)")
    if purge_images:
        r = subprocess.run([ei.RUNTIME, "images", "--format", "{{.Repository}}:{{.Tag}}"],
                           capture_output=True, text=True)
        imgs = [i for i in r.stdout.split() if i.split("/")[-2:-1] == ["llgenie"] or i.startswith("llgenie/")]
        imgs = [i for i in imgs if not i.startswith(("llgenie/test:", "llgenie/openspec:"))]
        if imgs:
            subprocess.run([ei.RUNTIME, "rmi", "-f", *imgs], capture_output=True)
        print(f"[uninstall] removed {len(imgs)} engine image(s)")
    else:
        print("[uninstall] engine images kept as a cache (make uninstall PURGE_IMAGES=1 removes them)")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--bin", default=str(Path.home() / "bin"))
    ap.add_argument("--arch", default=None, help="cpu|cuda|rocm|vulkan (default: detected)")
    ap.add_argument("--no-build", action="store_true", help="only pull published images (default)")
    ap.add_argument("--build", action="store_true", help="build an image that is not published")
    ap.add_argument("--ensure", default="", help="pull one engine's image for this backend + its start script")
    ap.add_argument("--test", action="store_true", help="run every start script with --version")
    ap.add_argument("--engines", default="", help="comma-separated engine ids, or 'all' (default: llama.cpp + Prism)")
    ap.add_argument("--uninstall", action="store_true", help="remove what install wrote, stop engine containers")
    ap.add_argument("--purge-images", action="store_true", help="with --uninstall: also remove the engine images")
    a = ap.parse_args(argv)
    bindir = Path(a.bin).expanduser()
    if a.uninstall:
        return uninstall(bindir, a.purge_images)
    if a.test:
        return test(bindir)
    # macOS: Docker runs in Colima; a stopped VM or a VM whose DNS does not answer is
    # repaired (restarted with explicit DNS) before any pull (issue #112). No-op on Linux.
    ei.ensure_container_env()
    arch = a.arch or detected_arch()
    if a.ensure:
        return ensure(bindir, a.ensure, arch, a.build)
    only = [e for e in a.engines.split(",") if e]
    return install(bindir, arch, a.build and not a.no_build, only or None)


if __name__ == "__main__":
    sys.exit(main())
